# This is a basic workflow to help you get started with Actions

name: docker installation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Decode and Use EC2 Private Key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > main_key.pem
          chmod 400 main_key.pem
      - name: Install docker on EC2
        # env:
        #   EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.91.102.110 >> ~/.ssh/known_hosts
          ssh -i "main_key.pem" ubuntu@3.91.102.110 << EOF
          sudo apt update
          sudo apt install docker.io -y
          EOF
